sudo: required
services:
  - docker

before_install:
  - docker build -t itsmrakhil/docker-react -f Dockerfile.dev .

script:
  - docker run itsmrakhil/docker-react yarn test --coverage

branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-685566201433"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
